server:
  port: 8066

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-group
      auto-offset-reset: earliest

  data:
    mongodb:
      uri: mongodb://mongodb:27017/mongo
      auto-index-creation: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true


kafka:
  topics:
    order-created: order-created # Payments Service получает
    order-payment-processed: order-payment-processed # Payments Service отправляет
    payment-failed: payment-failed # Payments Service отправляет

external:
  payment:
    service:
      url: https://randomnumberapi.com/api/v1.0/random?min=1&max=1000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false

#service:
#  user:
#    url: http://user-service:8088
#    methodGetUserById: /api/v1/users/