server:
  port: ${SERVER_PORT:8066}

spring:
  application:
    name: payment-service

  retry:
    enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
    topics:
      order-created: order-created
      order-payment-processed: order-payment-processed
      payment-failed: payment-failed

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/payment_db}
      database: ${SPRING_DATA_MONGODB_DATABASE:payment_db}
      auto-index-creation: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

external:
  payment:
    service:
      url: https://www.random.org/integers/?num=1&min=1&max=1000&col=1&base=10&format=plain&rnd=new

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false