server:
  port: 8099

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: orders-group

  liquibase:
    enabled: false
    default-schema: order_schema
    liquibase-schema: order_schema
    change-log: classpath:/db/changelog/db.changelog-master.xml
    clear-checksums: true

  datasource:
    url: jdbc:postgresql://postgres:5432/innowise_db?currentSchema=order_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: order_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  topics:
    order-created: order-created                    # Order Service отправляет
    order-payment-processed: order-payment-processed # Order Service получает
    payment-failed: payment-failed                   # Order Service получает

service:
  user:
    url: http://user-service:8088
    methodGetUserById: /api/v1/users/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false